### ISSUE TITLE
Missing dependency in 'six'

### ISSUE THREAD

**Issue by telenieko** [lino-framework/book#40]
Hi,
After cloning this repository and doing `pip install -e .` this happens:
(Using python 3.6.8)

```
 Using cached https://files.pythonhosted.org/packages/a4/db/9e9268337c11128ceabc71124aa960fa330d83fd3e85abfe2cddf1c7996c/lino-welfare-18.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lc/80799yss6klb3_ft_szyfgyr0000gn/T/pip-install-47n3rduj/lino-welfare/setup.py", line 3, in <module>
        exec (compile(open(fn, "rb").read(), fn, 'exec'))
      File "lino_welfare/setup_info.py", line 28, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
```

It is probably a missing dependency on `six` from `lino-welfare`, but I've not yet got that deep into lino.

**Comment by lsaffre** [comment]
Fixed. Thanks for reporting. Run git pull in your clone and then pip install again.

**Comment by lsaffre** [comment]
I also wrote quick install instructions at http://welfare.lino-framework.org/install/index.html

**Comment by telenieko** [comment]
Closing as reported fixed by @lsaffre
